## 실습 3-2-1. 랜덤 벡터 생성과 정렬
- 길이 10인 랜덤 벡터(1차원 배열)을 생성하고 이를 정렬한다
- 오름차순과 내림차순으로 한 번씩 정렬해 본다

In [ ]:
import numpy as np

In [6]:
arr = np.random.random(10)
arr.sort()

In [7]:
arr # 오름차순 정렬

array([ 0.030492  ,  0.12043689,  0.32015067,  0.33430422,  0.72236358,
        0.83430805,  0.88724013,  0.8975324 ,  0.91277164,  0.98039898])

In [8]:
arr[::-1].sort()

In [9]:
arr # 내림차순 정렬

array([ 0.98039898,  0.91277164,  0.8975324 ,  0.88724013,  0.83430805,
        0.72236358,  0.33430422,  0.32015067,  0.12043689,  0.030492  ])

## 실습 3-2-2. 벡터를 행렬로 변환하기
- 길이 9의 벡터(1차원 배열)를 생성하고 이를 3X3 크기의 행렬로 변환한다
    - NumPy의 arange() 함수를 이용해 0부터 8까지의 정수를 담은 1차원 배열을 생성한다
    - 이를 reshape() 함수로 2차원 배열로 변환한다

In [13]:
arr = np.arange(9)

In [16]:
arr = arr.reshape(3,3)

In [17]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 실습 3-2-3. 대각행렬(diagonal matrix)
- 실습 3-2-2에서 생성한 행렬을 대각행렬로 변환해 본다
    - 우선 행렬의 주대각 원소(대각선상에 있는 원소)만 1차원 배열로 출력해 본다
    - 3X3  대각행렬(정사각행렬의 주대각 성분 이외의 모든 성분이 0인 행렬)로 변환해 본다

In [20]:
arr = np.arange(9).reshape(3,3)
diag = np.diag(arr)

In [21]:
diag

array([0, 4, 8])

In [22]:
diag_mat = np.diag(np.diag(arr))

In [23]:
diag_mat

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

## 실습 3-2-4. 행렬 정규화(normalization)
- 정수로 이루어진 5X5 행렬을 만들고 이를 정규화해본다
    - randint() 함수를 이용해 1부터 100 사이의 정수로 이루어진 행렬을 생성한다
    - 행렬 내의 값들을 정규화한다

In [32]:
arr = np.random.randint(1, 100, size =(5,5))

In [33]:
arr

array([[ 2, 37,  7, 27, 14],
       [83, 64, 96, 95,  4],
       [26, 12, 44, 78, 33],
       [95, 92, 69, 90, 85],
       [34, 49, 10, 96, 82]])

In [36]:
arrMax, arrMin = arr.max(), arr.min()
arr_normalized = (arr - arrMin)/(arrMax - arrMin)

In [37]:
arr_normalized

array([[ 0.        ,  0.37234043,  0.05319149,  0.26595745,  0.12765957],
       [ 0.86170213,  0.65957447,  1.        ,  0.9893617 ,  0.0212766 ],
       [ 0.25531915,  0.10638298,  0.44680851,  0.80851064,  0.32978723],
       [ 0.9893617 ,  0.95744681,  0.71276596,  0.93617021,  0.88297872],
       [ 0.34042553,  0.5       ,  0.08510638,  1.        ,  0.85106383]])

## 실습 3-2.5. 행렬 곱(matrix multiplication)
- (2X3) 행렬과 (3X2) 행렬 사이의 곱 연산을 수행한다
    - np.dot() 함수를 활용한다

In [41]:
A = np.array([[1,2,3],[4,5,6]])

In [42]:
B = np.array([[1,2], [3,4], [5,6]])

In [43]:
result = np.dot(A, B)

In [44]:
result

array([[22, 28],
       [49, 64]])

## 실습 3-2-6. 주식 데이터 불러오기
- stock-data.csv의 데이터를 불러온다
    - 1열부터 4열(‘Open’, ‘High’, ‘Low’, ‘Volume’)까지의 데이터는 x_data로 저장하고 5열(‘Close’)의 데이터는 y_data로 저장한다
    - 즉, x_data의 shape은 (732,4), y_data의 shape은 (732,) 혹은 (732,1)이 되어야 한다

In [5]:
data = np.loadtxt('stock-data.csv', delimiter = ',')
data.shape

(732, 5)

In [6]:
x_data = data[:,:-1]

(732, 4)

In [7]:
y_data = data[:, -1]

(732,)

In [8]:
x_data.shape

(732, 4)

In [9]:
x_data

array([[  8.28659973e+02,   8.33450012e+02,   8.28349976e+02,
          1.24770000e+06],
       [  8.23020020e+02,   8.28070007e+02,   8.21655029e+02,
          1.59780000e+06],
       [  8.19929993e+02,   8.24400024e+02,   8.18979980e+02,
          1.28170000e+06],
       ...,
       [  5.66892592e+02,   5.67002574e+02,   5.56932537e+02,
          1.08000000e+04],
       [  5.61202549e+02,   5.66432590e+02,   5.58672539e+02,
          4.12000000e+04],
       [  5.68002570e+02,   5.68002570e+02,   5.52922516e+02,
          1.31000000e+04]])

In [10]:
y_data.shape

(732,)

In [11]:
y_data

array([ 831.659973,  828.070007,  824.159973,  818.97998 ,  820.450012,
        819.23999 ,  813.669983,  809.559998,  808.380005,  806.969971,
        801.340027,  801.48999 ,  798.530029,  795.695007,  796.789978,
        802.320007,  823.309998,  832.150024,  835.669983,  823.869995,
        819.309998,  805.02002 ,  802.174988,  806.070007,  804.609985,
        807.880005,  806.359985,  807.909973,  804.789978,  806.650024,
        806.150024,  794.02002 ,  786.900024,  786.140015,  771.820007,
        782.789978,  785.049988,  791.549988,  789.909973,  791.26001 ,
        794.559998,  796.419983,  794.200012,  790.799988,  797.849976,
        797.070007,  796.099976,  789.27002 ,  789.289978,  776.419983,
        771.190002,  759.109985,  762.52002 ,  750.5     ,  747.919983,
        758.039978,  770.840027,  768.23999 ,  761.679993,  760.98999 ,
        768.27002 ,  769.200012,  760.539978,  771.22998 ,  764.47998 ,
        758.48999 ,  736.080017,  754.02002 ,  762.559998,  785.309998,
        790.51001 ,  782.52002 ,  762.02002 ,  762.130005,  768.700012,
        783.609985,  784.539978,  795.369995,  795.349976,  799.070007,
        807.669983,  813.109985,  799.369995,  796.969971,  801.5     ,
        795.26001 ,  779.960022,  778.530029,  778.190002,  786.140015,
        783.070007,  785.940002,  775.080017,  776.859985,  776.469971,
        776.429993,  772.559998,  777.289978,  775.01001 ,  781.559998,
        783.01001 ,  774.210022,  786.900024,  787.210022,  776.219971,
        771.409973,  765.700012,  768.880005,  771.76001 ,  762.48999 ,
        759.690002,  769.02002 ,  759.659973,  775.320007,  780.349976,
        780.080017,  771.460022,  768.780029,  767.049988,  769.090027,
        772.150024,  769.539978,  769.409973,  769.640015,  772.080017,
        772.150024,  775.419983,  777.5     ,  779.909973,  777.140015,
        782.440002,  783.219971,  784.849976,  784.679993,  784.26001 ,
        781.76001 ,  782.219971,  771.609985,  773.179993,  771.070007,
        772.880005,  768.789978,  745.909973,  741.77002 ,  738.419983,
        739.77002 ,  742.73999 ,  738.630005,  741.190002,  736.960022,
        733.780029,  719.849976,  720.950012,  716.97998 ,  720.640015,
        715.090027,  705.630005,  695.359985,  697.77002 ,  694.950012,
        699.210022,  692.099976,  684.109985,  680.039978,  668.26001 ,
        675.219971,  701.869995,  697.460022,  695.940002,  693.710022,
        691.719971,  710.359985,  718.919983,  718.27002 ,  718.359985,
        719.409973,  728.580017,  728.280029,  716.650024,  716.549988,
        722.340027,  730.400024,  734.150024,  735.719971,  732.659973,
        724.119995,  725.27002 ,  720.090027,  704.23999 ,  709.73999 ,
        700.320007,  706.630005,  706.22998 ,  716.48999 ,  710.830017,
        713.309998,  715.289978,  723.179993,  712.900024,  711.119995,
        701.429993,  695.700012,  692.359985,  698.210022,  693.01001 ,
        691.02002 ,  705.840027,  708.140015,  723.150024,  718.77002 ,
        759.140015,  752.669983,  753.929993,  766.609985,  759.      ,
        753.200012,  751.719971,  743.090027,  736.099976,  739.150024,
        740.280029,  745.690002,  737.799988,  745.289978,  749.909973,
        744.950012,  750.530029,  744.77002 ,  733.530029,  735.299988,
        738.059998,  740.75    ,  742.090027,  737.599976,  737.780029,
        736.090027,  728.330017,  730.48999 ,  726.820007,  712.820007,
        705.23999 ,  693.969971,  695.159973,  710.890015,  712.419983,
        718.849976,  718.809998,  697.77002 ,  705.070007,  705.75    ,
        699.559998,  695.849976,  706.460022,  700.909973,  697.349976,
        708.400024,  691.      ,  682.400024,  683.109985,  684.119995,
        678.109985,  682.73999 ,  683.570007,  708.01001 ,  726.950012,
        764.650024,  752.      ,  742.950012,  730.960022,  699.98999 ,
        713.039978,  711.669983,  725.25    ,  706.590027,  698.450012,
        701.789978,  694.450012,  714.719971,  700.559998,  726.070007,
        716.030029,  714.469971,  726.390015,  743.619995,  742.580017,
        741.840027,  758.880005,  771.      ,  776.599976,  762.51001 ,
        748.400024,  750.309998,  750.      ,  747.77002 ,  739.309998,
        749.429993,  758.090027,  743.400024,  747.77002 ,  738.869995,
        749.460022,  751.609985,  762.369995,  763.25    ,  766.809998,
        752.539978,  762.380005,  767.039978,  742.599976,  750.26001 ,
        748.150024,  748.280029,  755.97998 ,  756.599976,  738.409973,
        740.      ,  725.299988,  728.960022,  717.      ,  731.22998 ,
        735.400024,  728.320007,  724.890015,  733.76001 ,  731.25    ,
        728.109985,  722.159973,  721.109985,  710.809998,  716.919983,
        712.950012,  708.48999 ,  712.780029,  702.      ,  651.789978,
        642.609985,  650.280029,  666.099976,  662.200012,  661.73999 ,
        651.159973,  652.299988,  646.669983,  643.609985,  639.159973,
        642.359985,  645.440002,  641.469971,  626.909973,  611.289978,
        608.419983,  594.969971,  594.890015,  611.969971,  625.799988,
        622.359985,  622.690002,  635.440002,  629.25    ,  642.900024,
        635.97998 ,  635.140015,  623.23999 ,  625.77002 ,  621.349976,
        612.719971,  614.659973,  600.700012,  606.25    ,  614.340027,
        597.789978,  618.25    ,  630.380005,  637.609985,  628.619995,
        582.059998,  589.609985,  612.47998 ,  646.830017,  660.900024,
        656.130005,  660.869995,  657.119995,  656.450012,  659.559998,
        660.780029,  633.72998 ,  635.299988,  642.679993,  643.780029,
        629.25    ,  631.210022,  625.609985,  632.590027,  631.929993,
        628.      ,  627.26001 ,  623.559998,  644.280029,  662.099976,
        662.299988,  663.02002 ,  672.929993,  579.849976,  560.219971,
        561.099976,  546.549988,  530.130005,  520.679993,  516.830017,
        525.02002 ,  522.859985,  523.400024,  521.840027,  520.51001 ,
        521.52002 ,  531.690002,  535.22998 ,  537.840027,  540.47998 ,
        538.190002,  536.690002,  536.72998 ,  529.26001 ,  528.150024,
        527.200012,  532.330017,  534.609985,  536.690002,  526.690002,
        526.830017,  533.330017,  536.700012,  540.309998,  539.179993,
        533.98999 ,  532.109985,  539.780029,  539.789978,  532.320007,
        540.109985,  542.51001 ,  539.27002 ,  537.359985,  532.299988,
        533.849976,  538.400024,  529.619995,  529.039978,  535.700012,
        538.219971,  530.700012,  524.219971,  530.799988,  540.780029,
        537.900024,  537.340027,  549.080017,  553.679993,  555.369995,
        565.062561,  547.002472,  539.367458,  533.972413,  535.382408,
        524.052386,  533.802391,  532.532429,  530.392405,  539.172466,
        540.012416,  540.782472,  541.612446,  537.022404,  536.767432,
        535.532417,  542.562439,  548.002468,  552.032502,  548.342512,
        555.172522,  558.787539,  570.192597,  558.81251 ,  560.362537,
        557.992512,  559.502513,  550.842471,  554.512509,  547.322503,
        555.512505,  551.182515,  555.012538,  568.852557,  567.687558,
        575.332609,  573.372583,  573.64261 ,  571.342601,  558.402511,
        555.482516,  543.872489,  536.092424,  531.912381,  538.952441,
        542.872432,  539.702422,  542.842443,  549.012501,  542.932472,
        535.972405,  536.942412,  527.832406,  531.002415,  527.582391,
        522.762349,  529.2424  ,  528.482381,  534.522445,  510.6623  ,
        510.002318,  518.63237 ,  535.212448,  539.952437,  534.392388,
        518.042373,  506.902294,  508.082288,  501.792271,  500.872267,
        496.182251,  492.552239,  496.172244,  502.682285,  501.102268,
        501.962262,  513.872306,  524.812404,  526.402397,  530.422394,
        530.332426,  534.032392,  528.772422,  530.592416,  524.872383,
        516.352313,  511.102319,  504.892295,  495.392242,  513.802351,
        518.662359,  528.34241 ,  526.062353,  533.37244 ,  526.982357,
        525.262369,  537.312445,  531.322384,  533.752389,  533.802391,
        541.832471,  540.372473,  541.082428,  539.272471,  537.502419,
        534.832438,  536.992415,  535.032449,  536.512399,  544.402446,
        545.38249 ,  547.312465,  550.292501,  547.492463,  541.012473,
        542.042458,  545.922484,  554.112486,  555.222525,  559.082538,
        550.312514,  549.33247 ,  548.902458,  540.772435,  539.782415,
        543.982471,  532.712427,  526.542369,  520.842349,  511.172305,
        524.512387,  530.032409,  537.942408,  533.212394,  544.492476,
        560.882518,  572.502582,  563.742534,  577.352614,  575.282606,
        570.082554,  568.272597,  577.36259 ,  576.362594,  577.1026  ,
        575.062581,  587.992634,  581.132634,  587.372648,  596.082692,
        589.272695,  584.772622,  579.95264 ,  573.102616,  575.622589,
        581.352659,  583.102636,  581.012615,  589.722659,  586.082672,
        581.982621,  577.942611,  577.332601,  571.602592,  569.202577,
        571.002557,  577.862619,  580.202654,  582.562642,  583.372664,
        584.492618,  586.862643,  582.162619,  573.482626,  574.652582,
        574.782577,  562.732562,  567.882551,  568.772565,  563.362525,
        566.376589,  565.072537,  573.152619,  566.072533,  571.602592,
        587.42265 ,  585.612633,  590.602697,  589.022681,  593.352671,
        595.982686,  594.742713,  589.472645,  595.082696,  573.732579,
        582.662648,  584.782659,  584.872627,  579.182645,  571.102563,
        576.08259 ,  571.092587,  582.252649,  584.732656,  582.33766 ,
        582.672624,  575.282606,  577.242632,  576.002598,  578.652627,
        564.622572,  564.952579,  556.362492,  554.902495,  553.372481,
        543.012465,  544.282488,  551.762475,  551.352476,  558.842499,
        560.552511,  562.122552,  556.332503,  553.902499,  544.662436,
        544.94244 ,  553.932488,  559.892559,  560.082534,  561.682564,
        565.952575,  552.702492,  545.062459,  538.942465,  529.772418,
        528.862391,  520.632362,  519.982324,  526.652412,  533.092437,
        529.922427,  518.732375,  511.002313,  509.962321,  515.14233 ,
        527.812392,  527.932411,  531.352435,  526.662388,  527.70241 ,
        517.152359,  516.182352,  525.162363,  526.942391,  534.812425,
        528.622414,  536.1024  ,  556.54249 ,  536.442444,  532.522392,
        530.602392,  540.952433,  564.142557,  554.902495,  538.152456,
        543.14246 ,  569.742571,  567.002574,  567.162558,  556.972503,
        559.992565,  558.462551])

## 실습 3-2-7. 당뇨 데이터 불러오기
- diabetes-data.csv의 데이터를 불러온다
    - 1열부터 8열까지의 데이터는 x_data로 저장하고 9열의 데이터는 y_data로 저장한다
    - 즉, x_data의 shape은 (759, 8), y_data의 shape은 (759,) 혹은 (759,1)이 되어야 한다

In [12]:
data = np.loadtxt('diabetes-data.csv', delimiter = ',')
data.shape

(759, 9)

In [13]:
x_data = data[:, :-1]
y_data = data[:, 5:6]

In [14]:
x_data.shape

(759, 8)

In [15]:
x_data

array([[-0.294118  ,  0.487437  ,  0.180328  , ...,  0.00149028,
        -0.53117   , -0.0333333 ],
       [-0.882353  , -0.145729  ,  0.0819672 , ..., -0.207153  ,
        -0.766866  , -0.666667  ],
       [-0.0588235 ,  0.839196  ,  0.0491803 , ..., -0.305514  ,
        -0.492741  , -0.633333  ],
       ...,
       [-0.411765  ,  0.21608   ,  0.180328  , ..., -0.219076  ,
        -0.857387  , -0.7       ],
       [-0.882353  ,  0.266332  , -0.0163934 , ..., -0.102832  ,
        -0.768574  , -0.133333  ],
       [-0.882353  , -0.0653266 ,  0.147541  , ..., -0.0938897 ,
        -0.797609  , -0.933333  ]])

In [16]:
y_data.shape

(759,)

In [17]:
y_data

array([ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,
        0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,
        1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
        1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,
        0.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,
        0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,
        1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,
        0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,
        0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,
        1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,
        0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,
        1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,
        0.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,
        1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,
        1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,
        0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,
        0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,
        0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,
        0.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,
        0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,
        1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,
        1.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        1.,  1.,  1.,  0.,  1.])

In [1]:
import pandas as pd

## 실습 3-2-8. 데이터프레임 생성하기
- 아래 내용의 데이터를 담은 데이터프레임을 생성해 본다
    - 1열부터 8열까지의 데이터는 x_data로 저장하고 9열의 데이터는 y_data로 저장한다
    - Title, Artist, Length는 String 타입으로, Year는 int 타입으로 저장한다

In [2]:
title = ['Skyfall', 'Lose Yourself', 'Another Brick in the Wall', 'Use Somebody', 'Treasure']
artist = ['Adele', 'Eminem', 'Pink Floyd', 'Kings of Leon', 'Bruno Mars']
length = ['4:46', '5:26', '3:59', '3:51', '2:58']
year = [2012, 2002, 1979, 2008, 2013]
data = pd.DataFrame({'Title': title, 'Artist': artist, 'Length': length, 'Year': year})

In [3]:
data

          Artist Length                      Title  Year
0          Adele   4:46                    Skyfall  2012
1         Eminem   5:26              Lose Yourself  2002
2     Pink Floyd   3:59  Another Brick in the Wall  1979
3  Kings of Leon   3:51               Use Somebody  2008
4     Bruno Mars   2:58                   Treasure  2013

## 실습 3-2-9. 데이터프레임 나누기
- 실습 3-2-8에서 생성된 데이터프레임에서 ‘Title’ 컬럼의 데이터만 추출한다
    - 추출한 데이터는 모두 소문자(lowercase)로 변환한 뒤 title_lowercase 이름의 리스트에 저장한다

In [4]:
title_lowercase = [t.lower() for t in data['Title']]

In [5]:
title_lowercase

['skyfall',
 'lose yourself',
 'another brick in the wall',
 'use somebody',
 'treasure']

## 실습 3-2-10. 엑셀 데이터 불러오기
- animals.xlsx 파일을 불러와 데이터프레임을 생성한다
    - 엑셀 파일의 첫 세 컬럼(name, hair, feathers)의 데이터만 포함하는 데이터프레임 animals를 생성한다
    - 참고: .loc[] 혹은 .iloc[] 를 통해 슬라이싱한다(refer to: https://stackoverflow.com/questions/10665889/how-to-take-column-slices-of-dataframe-in-pandas)

In [2]:
data = pd.read_excel('animals.xlsx')

In [ ]:
data

In [3]:
animals = data.loc[:, ['name', 'hair', 'feathers']]

In [ ]:
animals

## 실습 3-2-11. 엑셀 파일로 저장하기
- 실습 3-2-10에서 생성된 animals 데이터프레임의 데이터를 엑셀 파일로 저장한다
    - animals_sub.xlsx 이름으로 저장한다

In [13]:
animals.to_excel('animals_sub.xlsx')